US-505974 : embedded migration support

diff --git a/charts/pega/charts/hazelcast/templates/clustering-service-migration.yaml b/charts/pega/charts/hazelcast/templates/clustering-service-migration.yaml
--- a/charts/pega/charts/hazelcast/templates/clustering-service-migration.yaml
+++ b/charts/pega/charts/hazelcast/templates/clustering-service-migration.yaml
@@ -1,5 +1,5 @@
 {{ if and (and (eq (include "performDeployment" .) "true") (eq (include "isMigrationInit" .) "true"))
-   (and (eq (include "isHazelcastEnabled" .) "true") (eq (include "isClusteringServiceEnabled" .) "true")) }}
+   (eq (include "isClusteringServiceEnabled" .) "true") }}
 ---
 apiVersion: batch/v1
 kind: Job
@@ -7,6 +7,7 @@ metadata:
   name: {{ template "clusteringServiceName" . }}-migration-job
   namespace: {{ .Release.Namespace }}
 spec:
+  backoffLimit: 0
   template:
     metadata:
       name: {{ template "clusteringServiceName" . }}-migration-job
@@ -29,6 +30,8 @@ spec:
                 "content": {
                 	"SERVER_HOSTNAME": "{{ template "clusteringServiceName" . }}-service.{{ .Release.Namespace }}.svc.cluster.local",
                 	"CLUSTER_NAME": "{{ .Values.server.clustering_service_group_name }}",
+                    "HZ_USERNAME": "{{ .Values.username }}",
+                    "HZ_PASSWORD": "{{ .Values.password }}",
                 	"CLIENT_MODE_ENABLED": "true",
                 	"HZONK8S": "true"
                 }
@@ -54,7 +57,7 @@ spec:
 
               if  [ $mig_status == 'INITIALIZATION_FAILED' ] ; then
                  echo "V5 initialization failed..."
-                 exit
+                 exit 1
               fi
 
               # Migration Step
@@ -73,7 +76,7 @@ spec:
 
               if [ $mig_status == 'MIGRATION_FAILED' ] ; then
                  echo "Migration failed..."
-                 exit
+                 exit 1
               fi
 
               # Shutdown Step
@@ -89,8 +92,12 @@ spec:
                  sleep 30
                  mig_status="$(kubectl -n {{ .Release.Namespace }} exec $podname -- curl http://localhost:8080/prweb/api/CloudRemoteAPI/v1/pzcluster/hazelcast-v5-upgrade/status)"
               done
-
+              if [ $mig_status == 'SHUTDOWN_FAILED' ] ; then
+                 echo "Shutdown failed..."
+                 exit 1
+              fi
               echo "Status :: '$mig_status'"
+              exit
       restartPolicy: Never
 
 ---
