changes

diff --git a/.github/workflows/github-actions-go.yml b/.github/workflows/github-actions-go.yml
--- a/.github/workflows/github-actions-go.yml
+++ b/.github/workflows/github-actions-go.yml
@@ -21,7 +21,7 @@ jobs:
     if: always()
     steps:
       - run: |
-          echo "ABC" | (( grep "FAIL" -A 8 || true ))
+          echo "ABC" | { grep "FAIL" -A 8 || true }
           echo ${PIPESTATUS[0]} ${PIPESTATUS[1]}
       - run: sudo rm /usr/local/bin/helm
       
