only tag builds will deploy to gh-pages

diff --git a/.github/workflows/github-actions-build.yml b/.github/workflows/github-actions-build.yml
--- a/.github/workflows/github-actions-build.yml
+++ b/.github/workflows/github-actions-build.yml
@@ -89,7 +89,11 @@ jobs:
           export PATH=$PATH:$GITHUB_WORKSPACE/terratest/bin
           cd terratest/src/test
           dep ensure
-          
+          # grep "FAIL" -A 8 - filter unnecessary logs from the final output but show failing tests
+          #  ; test ${PIPESTATUS[0]} -eq 0 - check if go test was finished success. Without it pipe return exit code from last command.
+          # go test test/pega | grep "FAIL" -A 8 ; test ${PIPESTATUS[0]} -eq 0
+          # go test test/addons | grep "FAIL" -A 8 ; test ${PIPESTATUS[0]} -eq 0
+      
       - name: run go tests on pega
         run: |
           export GOPATH=$GITHUB_WORKSPACE/terratest
@@ -114,7 +118,7 @@ jobs:
   run-deploy-job:
     runs-on: ubuntu-18.04
     needs: [run-lint-job, run-remark-job, run-go-tests-job]
-    if: (github.event_name != 'pull_request' ) &&  success()
+    if: ( github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v') ) &&  success()
     steps:
       - name: Install Helm
         run: |
@@ -142,8 +146,6 @@ jobs:
 
 
       - name: deploy on github releases
-        if: |
-          github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v')
         uses: marvinpinto/action-automatic-releases@latest
         with:
           prerelease: false
@@ -154,7 +156,7 @@ jobs:
             pega-aws-eks-example.tar.gz
             pega-google-gke-example.tar.gz
             pega-pivotal-pks-example.tar.gz
-          repo_token: ${{ secrets.GH_ACTIONS_SECRET }}
+          repo_token: ${{ secrets.NEW_SECRET }}
 
       - name: deploy on github pages
         run: |
@@ -162,4 +164,4 @@ jobs:
           chmod 777 update_gh_pages.sh
           ./update_gh_pages.sh
         env:
-          GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_SECRET }}
+          GITHUB_TOKEN: ${{ secrets.NEW_SECRET }}
